# Generated by Django 5.1.2 on 2025-02-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(help_text="Specify a city (e.g. 'Manchester') or 'Online'.", max_length=255)),
                ('date', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('sports', 'Sports'), ('academic', 'Academic'), ('arts', 'Arts'), ('cultural', 'Cultural'), ('social', 'Social'), ('other', 'Other')], max_length=50)),
                ('keyword', models.CharField(help_text="Tag or keyword for searching (e.g. 'chess').", max_length=50)),
                ('is_free', models.BooleanField(default=True)),
                ('members_only', models.BooleanField(default=False)),
                ('capacity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('waitlisted', 'Waitlisted'), ('rejected', 'Rejected')], default='waitlisted', max_length=20)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
