# Generated by Django 5.1.2 on 2025-02-10 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_end_time_event_societies_event_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
    ]
