# Generated by Django 5.1.2 on 2025-02-11 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='society',
        ),
    ]
