# Generated by Django 5.1.6 on 2025-03-27 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='fee_general',
        ),
        migrations.RemoveField(
            model_name='event',
            name='fee_member',
        ),
    ]
