# Generated by Django 5.1.2 on 2025-03-23 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20250323_0001'),
    ]

    operations = [
    ]
