# Generated by Django 5.1.2 on 2025-02-13 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_society'),
        ('societies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='society',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='societies.society'),
        ),
    ]
