# Generated by Django 5.1.2 on 2025-03-23 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20250323_0003'),
    ]

    operations = [
    ]
