# Generated by Django 5.1.2 on 2025-02-15 00:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_society'),
        ('societies', '0003_society_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='society',
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='societies',
            field=models.ManyToManyField(to='societies.society'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
