# Generated by Django 5.1.2 on 2025-02-15 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_society_event_end_time_event_societies_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='societies',
            new_name='society',
        ),
    ]
