# Generated by Django 5.1.2 on 2025-03-23 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20250323_2239'),
    ]

    operations = [
    ]
