# Generated by Django 5.1.6 on 2025-03-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
