# Generated by Django 5.1.2 on 2025-02-10 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='event',
        ),
    ]
