# Generated by Django 5.1.6 on 2025-03-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
        ('societies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='society',
            field=models.ManyToManyField(blank=True, to='societies.society'),
        ),
    ]
