# Generated by Django 5.1.6 on 2025-03-26 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panels', '0001_initial'),
        ('societies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='society',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_society', to='societies.society'),
        ),
        migrations.AddField(
            model_name='image',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='panels.gallery'),
        ),
    ]
