# Generated by Django 5.1.6 on 2025-03-26 17:54

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0004_comment'),
        ('societies', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='unique_vote_per_option',
        ),
        migrations.RemoveField(
            model_name='question',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='created_by',
        ),
        migrations.AddField(
            model_name='poll',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 2, 17, 53, 13, 191426, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='poll',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='title',
            field=models.CharField(default='Untitled Poll', max_length=255),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='poll',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='societies.society'),
        ),
        migrations.AlterField(
            model_name='question',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='panels.poll'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('option', 'voted_by')},
        ),
    ]
