# Generated by Django 5.1.2 on 2025-02-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
