# Generated by Django 5.1.6 on 2025-03-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='joining_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
