# Generated by Django 5.1.6 on 2025-03-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='society',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
