# Generated by Django 5.1.2 on 2025-02-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0002_society_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='membership_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
