# Generated by Django 5.1.2 on 2025-02-24 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers_json', models.JSONField(blank=True, default=dict)),
                ('essay_text', models.TextField(blank=True)),
                ('portfolio_file', models.FileField(blank=True, null=True, upload_to='society_portfolios/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='societies.society')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='society_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocietyRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(choices=[('none', 'No Extra Requirements'), ('quiz', 'Quiz (Yes/No Questions)'), ('manual', 'Manual Approval (Essay/PDF)')], default='none', max_length=10)),
                ('threshold', models.PositiveIntegerField(default=1, help_text='Minimum number of correct answers required for auto-approval.')),
                ('requires_essay', models.BooleanField(default=False)),
                ('requires_portfolio', models.BooleanField(default=False)),
                ('society', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requirement', to='societies.society')),
            ],
        ),
        migrations.CreateModel(
            name='SocietyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('correct_answer', models.BooleanField()),
                ('society_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='societies.societyrequirement')),
            ],
        ),
    ]
