# Generated by Django 5.1.2 on 2025-02-18 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0003_society_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='societies', to=settings.AUTH_USER_MODEL),
        ),
    ]
