# Generated by Django 5.1.2 on 2025-02-23 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0003_society_membership_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='society',
            old_name='membership_fee',
            new_name='price_range',
        ),
    ]
