# Generated by Django 5.1.2 on 2025-02-22 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0004_society_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocietyExtraForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_schema', models.JSONField(help_text='JSON representation of the extra form fields.')),
            ],
        ),
        migrations.CreateModel(
            name='SocietyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('society_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('waitlisted', 'Waitlisted'), ('rejected', 'Rejected')], default='waitlisted', max_length=10)),
                ('extra_form_needed', models.BooleanField(default=False)),
                ('visibility', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Private', max_length=7)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='society_applications', to=settings.AUTH_USER_MODEL)),
                ('extra_form', models.OneToOneField(blank=True, help_text='Reference to the extra form for society registration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration', to='societies.societyextraform')),
            ],
        ),
        migrations.AddField(
            model_name='societyextraform',
            name='society_registration',
            field=models.OneToOneField(help_text='Custom form for society membership applications.', on_delete=django.db.models.deletion.CASCADE, related_name='extra_form_entry', to='societies.societyregistration'),
        ),
    ]
