# Generated by Django 5.1.2 on 2025-02-24 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0005_societyextraform_societyregistration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('announcements', 'Announcements'), ('events', 'Upcoming Events'), ('gallery', 'Gallery'), ('discussion', 'Discussion Board'), ('members', 'Member List'), ('custom', 'Custom HTML')], max_length=50)),
                ('position', models.PositiveIntegerField(default=0)),
                ('custom_html', models.TextField(blank=True, null=True)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='societies.society')),
            ],
        ),
    ]
