# Generated by Django 5.1.2 on 2025-02-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0006_widget'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='widget',
            options={'ordering': ['position']},
        ),
        migrations.AlterField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[('announcements', 'Announcements'), ('events', 'Events'), ('gallery', 'Gallery'), ('contacts', 'Contact Information'), ('featured', 'Featured Members'), ('leaderboard', 'Leaderboard'), ('news', 'News')], max_length=50),
        ),
    ]
