# Generated by Django 5.1.6 on 2025-03-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_annual_verification_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='annual_verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
